### PR TITLE
Updates to request for sending payment token

### PR DESCRIPTION
**Pull request by PharaohAsh**
Some updates to sending of payment token.

**New Sample Request:**
```
{
	"payment": {
		"instrument": {
			"type": "stored_card",
			"token": "some-long-string-here-yaddayadda",
			"verification_value": "123"
		},
		"payment_method_id": "stripe.card",
		"save_instrument": true
	}
}
```

Please take a look @tatiana-perry and let me know if I'm missing anything.

### CODE REVIEW

**Comment by tatiana-perry** [comment]
@PharaohAsh Thanks for this! I can update the instrument object with an actual example. 
Is the token the BC Payment Access Token or something else?
The verification_id I assume is the cvv code?

**Comment by PharaohAsh** [comment]
@tatiana-perry Yup, that's correct. It is the BC Payment Access Token we send to create/make payments.
The `verification_value` is indeed the cvv code for the card instrument.

**Comment by PharaohAsh** [comment]
Oh, I did a big lie.

The `token` is actually the "vaulted instrument token" or the "bigpay token" we have recorded for a stored card. I'm sorry! That's my bad.

**Comment by tatiana-perry** [comment]
Closing Pull Request. Updated the Vaulted Card Example here: https://bigcommerce-payments-api-beta.docs.stoplight.io/process-payment/payment/paymentspost

**Pull request closed without merging**
